-- ============================================================
-- LAND RECORD DATABASE - MULTIPLE RECORDS / LIVE DATA
-- ============================================================

create table if not exists public.land_records (
  id bigint generated by default as identity primary key,
  khatian text not null default '৩০২',
  owner text not null default 'দঃ আবদুল খালেক',
  dag_no text not null default '৪৯৬৯',
  survey text not null default 'আর এস',
  mouza text not null default 'আলাদিনগর',
  upazila text not null default 'বেগমগঞ্জ',
  district text not null default 'নোয়াখালী',
  division text not null default 'চট্টগ্রাম',
  record_date text not null default '২৪ আগস্ট ২০২৬',
  updated_at timestamptz not null default now()
);

-- Existing table হলে ID-কে automatic করার চেষ্টা
do $$
begin
  if exists (
    select 1
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'land_records'
      and a.attname = 'id'
      and a.attidentity = ''
  ) then
    alter table public.land_records
      alter column id add generated by default as identity;
  end if;
end $$;


-- পুরোনো record থাকলে সেটি থাকবে
insert into public.land_records
(khatian, owner, dag_no, survey, mouza, upazila, district, division, record_date)
select
'৩০২',
'দঃ আবদুল খালেক',
'৪৯৬৯',
'আর এস',
'আলাদিনগর',
'বেগমগঞ্জ',
'নোয়াখালী',
'চট্টগ্রাম',
'২৪ আগস্ট ২০২৬'
where not exists (
  select 1 from public.land_records
);


-- Row Level Security
alter table public.land_records enable row level security;


-- সবাই record দেখতে পারবে
drop policy if exists "Public can read land record"
on public.land_records;

create policy "Public can read land record"
on public.land_records
for select
to anon, authenticated
using (true);


-- Admin শুধু নিজের account দিয়ে পরিবর্তন করতে পারবে
drop policy if exists "Admin can write land record"
on public.land_records;

create policy "Admin can write land record"
on public.land_records
for all
to authenticated
using (
  (auth.jwt() ->> 'email') = 'dlrms.land.gov.bd.jdjsj@gmail.com'
)
with check (
  (auth.jwt() ->> 'email') = 'dlrms.land.gov.bd.jdjsj@gmail.com'
);
